import React, { Component } from 'react';
import { Container, Content, Form, Item, Input, Label, Card, CardItem, Left, Button, Text, Footer, FooterTab } from 'native-base';
import { StyleSheet, View, Modal, TouchableOpacity, Image, ImageBackground, Linking, ActivityIndicator} from 'react-native';
import Icon from 'react-native-vector-icons/FontAwesome';
import I18n from 'react-native-i18n';
import AsyncStorage from '@react-native-async-storage/async-storage';
import axios from 'axios';

  I18n.fallbacks = true;
  I18n.translations = {
    'en': require('./translations/en'),
    'ar': require('./translations/ar'),
  }

export default class TermsConditions extends Component {
  constructor(props) {
    super(props);
    this.state = {
      // benefits: '',
      // loading: false,
    }
  }

  componentDidMount = async () => {
    this._navListener = this.props.navigation.addListener('focus', () => {
      this.setState({ value: true });
    });
  }
  
  render() {
    return (
      <Container>
        <Content padder>
        <View style={{ marginTop: 10 }}>
          <Card style={{ padding: 10}}>
             {/*<CardItem bordered>*/}
                <Text style={{ color: '#3C2949' }}>
                  <Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 17 }}>Terms & Conditions {"\n"}</Text>
                  Updated at 2021-07-13 {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>General Terms {"\n"}{"\n"}</Text>
                  By accessing and placing an order with Insure, you
                  confirm that you are in agreement with and bound by
                  the terms of service contained in the Terms & Conditions
                  outlined below. These terms apply to the entire website
                  and any email or other type of communication between
                  you and Insure. Under no circumstances shall Insure team is liable for
                  any direct, indirect, special, incidental, or consequential
                  damages, including, but not limited to, loss of data or
                  profit, arising out of the use, or the inability to use, the
                  materials on this site, even if Insure team or an
                  authorized representative has been advised of the
                  possibility of such damages. If your use of materials from
                  this site results in the need for servicing, repair, or
                  correction of equipment or data, you assume any costs
                  thereof.
                  Insure will not be responsible for any outcome that may
                  occur during the course of usage of our resources. We
                  reserve the right to change prices and revise the
                  resources usage policy at any moment. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>License {"\n"}{"\n"}</Text>
                  Insure grants you a revocable, non-exclusive, non- transferable, limited license to download, install and use
                  the app strictly in accordance with the terms of this
                  Agreement. These Terms & Conditions are a contract between you
                  and Insure (referred to in these Terms & Conditions as "Insure", "us", and "we" or "our"), the provider of the
                  Insure website, and the services accessible from the
                  Insure website (which is collectively referred to in these
                  Terms & Conditions as the "Insure Service"). You are agreeing to be bound by these Terms &
                  Conditions. If you do not agree to these Terms &
                  Conditions, please do not use the Insure Service. In these
                  Terms & Conditions, "you" refers both to you as an
                  individual and to the entity you represent. If you violate
                  any of these Terms & Conditions, we reserve the right to
                  cancel your account or block access to your account
                  without notice. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Meanings {"\n"}{"\n"}</Text>
                  For this Terms & Conditions: -Cookie: a small amount of data generated by a website
                  and saved by your web browser. It is used to identify
                  your browser, provide analytics, and remember
                  information about you such as your language preference
                  or login information. -Company: when this policy mentions “Company,” "we,""us," or "our,"" it refers to Global Future Solutions, (Abu
                  Dhabi) that is responsible for your information under
                  these Terms & Conditions. -Country: where Insure or the owners/founders of Insure
                  are based, in this case, is the United Arab Emirates
                  -Device: any internet-connected device such as a phone, tablet, computer, or any other device that can be used to
                  visit Insure and use the services. -Service: refers to the service provided by Insure as
                  described in the relative terms (if available) and on this
                  platform. -Third-party service: refers to advertisers, contest
                  sponsors, promotional and marketing partners, and
                  others who provide our content or whose products or
                  services we think may interest you. -Website: Insure’s site, which can be accessed via this
                  URL: -You: a person or entity that is registered with Insure to
                  use the Services. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Restrictions {"\n"}{"\n"}</Text>
                  You agree not to, and you will not permit others to: -License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially
                  exploit the app or make the platform available to any
                  third party. -Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the app. -Remove, alter or obscure any proprietary notice
                  (including any notice of copyright or trademark) of
                  Insure or its affiliates, partners, suppliers, or the
                  licensors of the app. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Return and Refund Policy {"\n"}{"\n"}</Text>
                  Thanks for shopping at Insure. We appreciate the fact
                  that you like to buy the stuff we build. We also want to
                  make sure you have a rewarding experience while you’re
                  exploring, evaluating, and purchasing our products. As with any shopping experience, there are terms and
                  conditions that apply to transactions at Insure. We’ll be
                  as brief as our attorneys will allow. The main thing to
                  remember is that by placing an order or making a
                  purchase at Insure, you agree to the terms along with
                  Insure's Privacy Policy.
                  If, for any reason, you are not completely satisfied with
                  any good or service that we provide, don't hesitate to
                  contact us and we will discuss any of the issues you are
                  going through with our product. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>You’re Suggestions {"\n"}{"\n"}</Text>
                  Any feedback, comments, ideas, improvements or
                  suggestions (collectively, "Suggestions") provided by you
                  to Insure with respect to the app shall remain the sole
                  and exclusive property of Insure.
                  Insure shall be free to use, copy, modify, publish, or
                  redistribute the Suggestions for any purpose and in any
                  way without any credit or any compensation to you. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>You’re Consent {"\n"}{"\n"}</Text>
                  We've updated our Terms & Conditions to provide you
                  with complete transparency into what is being set when
                  you visit our site and how it's being used. By using our
                  app, registering an account, or making a purchase, you
                  hereby consent to our Terms & Conditions. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Links to Other Websites {"\n"}{"\n"}</Text>
                  These Terms & Conditions apply only to the Services. The
                  Services may contain links to other websites not
                  operated or controlled by Insure. We are not responsible
                  for the content, accuracy, or opinions expressed in such
                  websites, and such websites are not investigated, monitored, or checked for accuracy or completeness by
                  us. Please remember that when you use a link to go from
                  the Services to another website, our Terms & Conditions
                  are no longer in effect. You’re browsing and interaction
                  on any other website, including those that have a link on
                  our platform, is subject to that website’s own rules and
                  policies. Such third parties may use their own cookies or
                  other methods to collect information about you. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Cookies {"\n"}{"\n"}</Text>
                  Insure uses "Cookies" to identify the areas of our
                  website that you have visited. A cookie is a small piece of
                  data stored on your computer or mobile device by your
                  web browser. We use cookies to enhance the
                  performance and functionality of our app but are non- essential to their use. However, without these cookies, certain functionality like videos may become unavailable
                  or you would be required to enter your login details
                  every time you visit the app as we would not be able to
                  remember that you had logged in previously. Most web
                  browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to
                  access functionality on our website correctly or at all. We
                  never place Personally Identifiable Information in
                  cookies. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Changes to Our Terms & Conditions {"\n"}{"\n"}</Text>
                  You acknowledge and agree that Insure; may stop
                  (permanently or temporarily) providing the Service (or
                  any features within the Service) to you or to users
                  generally at Insure’s sole discretion, without prior notice
                  to you. You may stop using the Service at any time. You
                  do not need to specifically inform Insure; when you stop
                  using the Service. You acknowledge and agree that if
                  Insure; disables access to your account, you may be
                  prevented from accessing the Service, your account
                  details, or any files or other materials which are
                  contained in your account If we decide to change our Terms & Conditions, we will
                  post those changes on this page, and/or update the
                  Terms & Conditions modification date below. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Modifications to Our app {"\n"}{"\n"}</Text>
                  Insure reserves the right to modify, suspend or
                  discontinue, temporarily or permanently, the app or any
                  service to which it connects, with or without notice and
                  without liability to you. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Updates to Our app {"\n"}{"\n"}</Text>
                  Insure may from time to time provide enhancements or
                  improvements to the features/ functionality of the app, which may include patches, bug fixes, updates, upgrades, and other modifications ("Updates"). Updates may modify or delete certain features and/or
                  functionalities of the app. You agree that Insure has no
                  obligation to (i) provide any Updates, or (ii) continue to
                  provide or enable any particular features and/or
                  functionalities of the app to you. You further agree that all Updates will be (i) deemed to
                  constitute an integral part of the app, and (ii) subject to
                  the terms and conditions of this Agreement. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Third-Party Services {"\n"}{"\n"}</Text>
                  We may display, include or make available third-party
                  content (including data, information, applications, and
                  other products services) or provide links to third-party
                  websites or services ("Third- Party Services"). You acknowledge and agree that Insure shall not be
                  responsible for any Third-Party Services, including their
                  accuracy, completeness, timeliness, validity, copyright
                  compliance, legality, decency, quality, or any other
                  aspect thereof. Insure does not assume and shall not
                  have any liability or responsibility to you or any other
                  person or entity for any Third-Party Services. Third-Party Services and links thereto are provided solely
                  as a convenience to you and you access and use them
                  entirely at your own risk and subject to such third
                  parties' terms and conditions. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Term and Termination {"\n"}{"\n"}</Text>
                  This Agreement shall remain in effect until terminated by
                  you or Insure.
                  Insure may, in its sole discretion, at any time and for any
                  or no reason, suspend or terminate this Agreement with
                  or without prior notice. This Agreement will terminate immediately, without
                  prior notice from Insure, in the event that you fail to
                  comply with any provision of this Agreement. You may also terminate this Agreement by deleting the app and
                  all copies thereof from your computer. Upon termination of this Agreement, you shall cease all
                  use of the app and delete all copies of the app from your
                  computer. Termination of this Agreement will not limit any of
                  Insure's rights or remedies at law or in equity in case of
                  breach by you (during the term of this Agreement) of
                  any of your obligations under the present Agreement. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Copyright Infringement Notice {"\n"}{"\n"}</Text>
                  If you are a copyright owner or such owner’s agent and
                  believe any material on our app constitutes an
                  infringement on your copyright, please contact us setting
                  forth the following information: (a) a physical or
                  electronic signature of the copyright owner or a person
                  authorized to act on his behalf; (b) identification of the
                  material that is claimed to be infringing; (c) your contact
                  information, including your address, telephone number, and an email; (d) a statement by you that you have a
                  good faith belief that use of the material is not
                  authorized by the copyright owners; and (e) the
                  statement that the information in the notification is
                  accurate, and, under penalty of perjury you are
                  authorized to act on behalf of the owner. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Indemnification {"\n"}{"\n"}</Text>
                  You agree to indemnify and hold Insure and its parents, subsidiaries, affiliates, officers, employees, agents, partners, and licensors (if any) harmless from any claim
                  or demand, including reasonable attorneys' fees, due to
                  or arising out of your: (a) use of the app; (b) violation of
                  this Agreement or any law or regulation; or (c) violation
                  of any right of a third party. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>No Warranties {"\n"}{"\n"}</Text>
                  The app is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any
                  kind. To the maximum extent permitted under
                  applicable law, Insure, on its own behalf and on behalf of
                  its affiliates and its and their respective licensors and
                  service providers, expressly disclaims all warranties, whether express, implied, statutory, or otherwise, with
                  respect to the app, including all implied warranties of
                  merchantability, fitness for a particular purpose, title and
                  non-infringement, and warranties that may arise out of
                  course of dealing, course of performance, usage or trade
                  practice. Without limitation to the foregoing, Insure
                  provides no warranty or undertaking and makes no
                  representation of any kind that the app will meet your
                  requirements, achieve any intended results, be
                  compatible or work with any other software, , systems or
                  services, operate without interruption, meet any
                  performance or reliability standards or be error-free or
                  that any errors or defects can or will be corrected.
                  Without limiting the foregoing, neither Insure nor any
                  Insure's provider makes any representation or warranty
                  of any kind, express or implied: (i) as to the operation or
                  availability of the app, or the information, content, and
                  materials or products included thereon; (ii) that the app
                  will be uninterrupted or error-free; (iii) as to the
                  accuracy, reliability, or currency of any information or
                  content provided through the app; or (iv) that the app,
                  its servers, the content, or e-mails sent from or on behalf
                  of Insure are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful
                  components. Some jurisdictions do not allow the exclusion of or
                  limitations on implied warranties or the limitations on
                  the applicable statutory rights of a consumer, so some or
                  all of the above exclusions and limitations may not apply
                  to you. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Limitation of Liability {"\n"}{"\n"}</Text>
                  Notwithstanding any damages that you might incur, the
                  entire liability of Insure and any of its suppliers under
                  any provision of this Agreement and your exclusive
                  remedy for all of the foregoing shall be limited to the
                  amount actually paid by you for the app. To the maximum extent permitted by applicable law, in
                  no event shall Insure or its suppliers be liable for any
                  special, incidental, indirect, or consequential damages
                  whatsoever (including, but not limited to, damages for
                  loss of profits, for loss of data or other information, for
                  business interruption, for personal injury, for loss of
                  privacy arising out of or in any way related to the use of
                  or inability to use the app, third-party software and/or
                  third-party hardware used with the app, or otherwise in
                  connection with any provision of this Agreement), even
                  if Insure or any supplier has been advised of the
                  possibility of such damages and even if the remedy fails
                  of its essential purpose. Some states/jurisdictions do not allow the exclusion or
                  limitation of incidental or consequential damages, so the
                  above limitation or exclusion may not apply to you. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Severability {"\n"}{"\n"}</Text>
                  If any provision of this Agreement is held to be
                  unenforceable or invalid, such provision will be changed
                  and interpreted to accomplish the objectives of such
                  provision to the greatest extent possible under
                  applicable law and the remaining provisions will
                  continue in full force and effect. This Agreement, together with the Privacy Policy and any
                  other legal notices published by Insure on the Services, shall constitute the entire agreement between you and
                  Insure concerning the Services. If any provision of this
                  Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not
                  affect the validity of the remaining provisions of this
                  Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be
                  deemed a further or continuing waiver of such term or
                  any other term, and Insure’s failure to assert any right or
                  provision under this Agreement shall not constitute a
                  waiver of such right or provision. YOU AND Insure AGREE
                  THAT ANY CAUSE OF ACTION ARISING OUT OF OR
                  RELATED TO THE SERVICES MUST COMMENCE WITHIN
                  ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY
                  BARRED. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Waiver {"\n"}{"\n"}</Text>
                  Except as provided herein, the failure to exercise a right
                  or to require performance of an obligation under this
                  Agreement shall not affect a party's ability to exercise
                  such right or require such performance at any time
                  thereafter nor shall be the waiver of a breach constitute
                  waiver of any subsequent breach. No failure to exercise and no delay in exercising, on the
                  part of either party, any right or any power under this
                  Agreement shall operate as a waiver of that right or
                  power. Nor shall any single or partial exercise of any
                  right or power under this Agreement preclude further
                  exercise of that or any other right granted herein. In the
                  event of a conflict between this Agreement and any
                  applicable purchase or other terms, the terms of this
                  Agreement shall govern. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Amendments to this Agreement {"\n"}{"\n"}</Text>
                  Insure reserves the right, at its sole discretion, to modify
                  or replace this Agreement at any time. If a revision is a
                  material we will provide at least 30 days' notice prior to
                  any new terms taking effect. What constitutes a material
                  change will be determined at our sole discretion. By continuing to access or use our app after any
                  revisions become effective, you agree to be bound by
                  the revised terms. If you do not agree to the new terms, you are no longer authorized to use Insure. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Entire Agreement {"\n"}{"\n"}</Text>
                  The Agreement constitutes the entire agreement
                  between you and Insure regarding your use of the app
                  and supersedes all prior and contemporaneous written
                  or oral agreements between you and Insure. You may be subject to additional terms and conditions
                  that apply when you use or purchase other Insure’s
                  services, which Insure will provide to you at the time of
                  such use or purchase. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Updates to Our Terms {"\n"}{"\n"}</Text>
                  We may change our Service and policies, and we may need to make changes to these Terms so that they
                  accurately reflect our Service and policies. Unless
                  otherwise required by law, we will notify you (for
                  example, through our Service) before we make changes
                  to these Terms and give you an opportunity to review
                  them before they go into effect. Then, if you continue to
                  use the Service, you will be bound by the updated
                  Terms. If you do not want to agree to these or any
                  updated Terms, you can delete your account. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Intellectual Property {"\n"}{"\n"}</Text>
                  The app and its entire contents, features, and
                  functionality (including but not limited to all information, software, text, displays, images, video and audio, and
                  the design, selection, and arrangement thereof), are
                  owned by Insure, its licensors, or other providers of such
                  material and are protected by the United Arab Emirates
                  and international copyright, trademark, patent, trade
                  secret and other intellectual property or proprietary
                  rights laws. The material may not be copied, modified, reproduced, downloaded, or distributed in any way, in
                  whole or in part, without the express prior written
                  permission of Insure, unless and except as is expressly
                  provided in these Terms & Conditions. Any unauthorized
                  use of the material is prohibited. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Agreement to Arbitrate {"\n"}{"\n"}</Text>
                  This section applies to any dispute EXCEPT IT DOESN’T
                  INCLUDE A DISPUTE RELATING TO CLAIMS FOR
                  INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE
                  ENFORCEMENT OR VALIDITY OF YOUR OR Insure’s
                  INTELLECTUAL PROPERTY RIGHTS. The term “dispute” means any dispute, action, or other controversies
                  between you and Insure concerning the Services or this
                  agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable
                  basis. “Dispute” will be given the broadest possible
                  meaning allowable under law. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Notice of Dispute {"\n"}{"\n"}</Text>
                  In the event of a dispute, you or Insure must give the
                  other a Notice of Dispute, which is a written statement
                  that sets forth the name, address, and contact
                  information of the party giving it, the facts giving rise to
                  the dispute, and the relief requested. You must send any
                  Notice of Dispute via email to: info@gfs.ae. Insure will
                  send any Notice of Dispute to you by mail to your
                  address if we have it, or otherwise to your email address. You and Insure will attempt to resolve any dispute
                  through informal negotiation within sixty (60) days from
                  the date the Notice of Dispute is sent. After sixty (60)
                  days, you or Insure may commence arbitration. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Binding Arbitration {"\n"}{"\n"}</Text>
                  If you and Insure don’t resolve any dispute by informal
                  negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as
                  described in this section. You are giving up the right to
                  litigate (or participate in as a party or class member) all
                  disputes in court before a judge or jury. The dispute shall
                  be settled by binding arbitration in accordance with the
                  commercial arbitration rules of the American Arbitration
                  Association. Either party may seek any interim or
                  preliminary injunctive relief from any court of competent
                  jurisdiction, as necessary to protect the party’s rights or
                  property pending the completion of arbitration. Any and
                  all legal, accounting, and other costs, fees, and expenses
                  incurred by the prevailing party shall be borne by the
                  non-prevailing party. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Submissions and Privacy {"\n"}{"\n"}</Text>
                  In the event that you submit or post any ideas, creative
                  suggestions, designs, photographs, information, advertisements, data, or proposals, including ideas for
                  new or improved products, services, features, technologies, or promotions, you expressly agree that
                  such submissions will automatically be treated as non- confidential and non-proprietary and will become the
                  sole property of Insure without any compensation or
                  credit to you whatsoever. Insure and its affiliates shall
                  have no obligations with respect to such submissions or
                  posts and may use the ideas contained in such
                  submissions or posts for any purposes in any medium in
                  perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services
                  using such ideas. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Promotions {"\n"}{"\n"}</Text>
                  Insure may, from time to time, include contests, promotions, sweepstakes, or other activities
                  (“Promotions”) that require you to submit material or
                  information concerning yourself. Please note that all
                  Promotions may be governed by separate rules that may
                  contain certain eligibility requirements, such as
                  restrictions as to age and geographic location. You are
                  responsible to read all Promotions rules to determine
                  whether or not you are eligible to participate. If you
                  enter any Promotion, you agree to abide by and comply
                  with all Promotions Rules. Additional terms and conditions may apply to purchases
                  of goods or services on or through the Services, which
                  terms and conditions are made a part of this Agreement
                  by this reference. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Typographical Errors {"\n"}{"\n"}</Text>
                  In the event a product and/or service is listed at an
                  incorrect price or with incorrect information due to
                  typographical error, we shall have the right to refuse or
                  cancel any orders placed for the product and/or service
                  listed at the incorrect price. We shall have the right to
                  refuse or cancel any such order whether or not the order has been confirmed and your credit card charged. If your
                  credit card has already been charged for the purchase
                  and your order is canceled, we shall immediately issue a
                  credit to your credit card account or other payment
                  accounts in the amount of the charge. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Miscellaneous {"\n"}{"\n"}</Text>
                  If for any reason a court of competent jurisdiction finds
                  any provision or portion of these Terms & Conditions to
                  be unenforceable, the remainder of these Terms &
                  Conditions will continue in full force and effect. Any
                  waiver of any provision of these Terms & Conditions will
                  be effective only if in writing and signed by an authorized
                  representative of Insure. Insure will be entitled to
                  injunctive or other equitable relief (without the
                  obligations of posting any bond or surety) in the event of
                  any breach or anticipatory breach by you. Insure
                  operates and controls the Insure Service from its offices
                  in the United Arab Emirates. The Service is not intended
                  for distribution to or use by any person or entity in any
                  jurisdiction or country where such distribution or use
                  would be contrary to law or regulation. Accordingly, those persons who choose to access the Insure Service
                  from other locations do so on their own initiative and
                  are solely responsible for compliance with local laws, if
                  and to the extent local laws are applicable. These Terms
                  & Conditions (which include and incorporate the Insure
                  Privacy Policy) contain the entire understanding, and
                  supersedes all prior understandings, between you and
                  Insure concerning its subject matter, and cannot be
                  changed or modified by you. The section headings used
                  in this Agreement are for convenience only and will not
                  be given any legal import. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Disclaimer {"\n"}{"\n"}</Text>
                  Insure is not responsible for any content, code, or any
                  other imprecision.
                  Insure does not provide warranties or guarantees.
                  In no event shall Insure be liable for any special, direct,
                  indirect, consequential, or incidental damages or any
                  damages whatsoever, whether in an action of contract, negligence or other torts, arising out of or in connection
                  with the use of the Service or the contents of the
                  Service. Insure reserves the right to make additions, deletions, or modifications to the contents of the Service
                  at any time without prior notice. The Insure Service and its contents are provided "as is" and "as available" without any warranty or
                  representations of any kind, whether express or implied.
                  Insure is a distributor and not a publisher of the content
                  supplied by third parties; as such, Insure exercises no
                  editorial control over such content and makes no
                  warranty or representation as to the accuracy, reliability, or currency of any information, content, service, or
                  merchandise provided through or accessible via the Insure Service. Without limiting the foregoing, Insure
                  specifically disclaims all warranties and representations
                  in any content transmitted on or in connection with the
                  Insure Service or on sites that may appear as links on the
                  Insure Service, or in the products provided as a part of, or otherwise in connection with, the Insure Service,
                  including without limitation any warranties of
                  merchantability, fitness for a particular purpose or noninfringement of third party rights. No oral advice or
                  written information given by Insure or any of its
                  affiliates, employees, officers, directors, agents, or the
                  like will create a warranty. Price and availability
                  information is subject to change without notice. Without
                  limiting the foregoing, Insure does not warrant that the
                  Insure Service will be uninterrupted, uncorrupted, timely, or error-free. {"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold' }}>Contact Us {"\n"}{"\n"}</Text>
                  Don't hesitate to contact us if you have any questions. -Via Email: info@gfs.ae {"\n"}{"\n"}{"\n"}{"\n"}



                  <Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 17 }}>البنود و الظروف {"\n"}</Text>
                     تم التحديث في 2021-07-13{"\n"}{"\n"}
                  <Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>شروط عامة {"\n"}{"\n"}</Text>
                  من خلال الوصول إلى طلب وتقديمه مع Insure ، فإنك تؤكد أنك توافقوتلتزم بشروط الخدمة الواردة في الشروط والأحكام الموضحة أدناه. تنطبق هذه الشروط على موقع الويب بالكامل وأي بريد إلكتروني أو أي نوع آخر من الاتصالات بينك وبين Insure. 

لا يتحمل فريق التأمين تحت أي ظرف من الظروف المسؤولية عن أي أضرار مباشرة أو غير مباشرة أو خاصة أو عرضية أو تبعية ، بما في ذلك ، على سبيل المثال لا الحصر ، فقدان البيانات أو الأرباح ، الناشئة عن استخدام المواد الموجودة في هذا الموقع ، حتى لو تم إخطار فريق التأمين أو ممثل مفوض بإمكانية حدوث مثل هذه الأضرار. إذا أدى استخدامك لمواد من هذا الموقع إلى الحاجة إلى خدمة أو إصلاح أو تصحيح المعدات أو البيانات ، فإنك تتحمل أي تكاليف لذلك. لن تكون Insure مسؤولة عن أي نتيجة قد تحدث أثناء استخدام مواردنا. نحتفظ بالحق في تغيير الأسعار ومراجعة سياسة استخدام الموارد في أي لحظة. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>رخصة {"\n"}{"\n"}</Text>
                  

يمنحك Insure ترخيصًا محدودًا وقابلًا للإلغاء وغير حصري وغير قابل للتحويل لتنزيل التطبيق وتثبيته واستخدامه وفقًا لشروط هذه الاتفاقية بدقة. 

 

 

 

هذه الشروط والأحكام هي عقد بينك وبين شركة Insure (يشار إليها في هذه الشروط والأحكام باسم "مؤمن" و "نحن" و "نحن" أو "خاصتنا") ، ومزود موقع التأمين والخدمات التي يمكن الوصول إليها من موقع التأمين على شبكة الإنترنت (المشار إليه إجمالاً في هذه الشروط والأحكام باسم "خدمة التأمين"). 

 

 

أنت توافق على الالتزام بهذه الشروط والأحكام. إذا كنت لا توافق على هذه الشروط والأحكام ، فيرجى عدم استخدام خدمة التأمين. في هذه الشروط والأحكام ، تشير كلمة "أنت" إليك كفرد وإلى الكيان الذي تمثله. إذا انتهكت أيًا من هذه الشروط والأحكام ، فإننا نحتفظ بالحق في إلغاء حسابك أو منع الوصول إلى حسابك دون إشعار.  
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>المعاني {"\n"}{"\n"}</Text>


لهذه الشروط والأحكام: 

-Cookie: كمية صغيرة من البيانات يتم إنشاؤها بواسطة موقع ويب وحفظها بواسطة متصفح الويب الخاص بك. يتم استخدامه لتحديد متصفحك ، وتقديم التحليلات ، وتذكر معلومات عنك مثل تفضيلات اللغة أو معلومات تسجيل الدخول. 

-الشركة: عندما تشير هذه السياسة إلى "الشركة" أو "نحن" أو "لنا" أو "خاصتنا" ، فإنها تشير إلى Global Future Solutions (أبو ظبي) المسؤولة عن معلوماتك بموجب هذه الشروط والأحكام. 

-الدولة: حيث يقع مقر المؤمن عليه أو أصحاب / مؤسسو التأمين ، في هذه الحالة ، هو دولة الإمارات العربية المتحدة 

- الجهاز: أي جهاز متصل بالإنترنت مثل الهاتف أو الجهاز اللوحي أو الكمبيوتر أو أي جهاز آخر يمكن استخدامه لزيارة Insure واستخدام الخدمات. 

- الخدمة: تشير إلى الخدمة المقدمة من قبل Insure كما هو موضح في المصطلحات ذات الصلة (إن وجدت) وعلى هذا النظام الأساسي. 

- خدمة الطرف الثالث: تشير إلى المعلنين ورعاة المسابقة والشركاء الترويجيين والتسويق وغيرهم ممن يقدمون المحتوى الخاص بنا أو الذين نعتقد أن منتجاتهم أو خدماتهم قد تثير اهتمامك. 

-Website: موقع Insure ، والذي يمكن الوصول إليه عبر عنوان URL هذا: 

- أنت: شخص أو كيان مسجل لدى المؤمن لاستخدام الخدمات. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>قيود {"\n"}{"\n"}</Text>


أنت توافق على عدم القيام بما يلي ، ولن تسمح للآخرين بما يلي: 

-ترخيص التطبيق أو بيعه أو تأجيره أو تأجيره أو التنازل عنه أو توزيعه أو نقله أو استضافته أو الاستعانة بمصادر خارجية أو الكشف عن التطبيق أو استغلاله تجاريًا بطريقة أخرى أو إتاحة النظام الأساسي لأي طرف ثالث. 

- تعديل أو عمل أعمال مشتقة من أي جزء من التطبيق أو تفكيكه أو فك تشفيره أو عكسه أو إجراء هندسة عكسية له. 

-إزالة أو تغيير أو حجب أي إشعار ملكية (بما في ذلك أي إشعار بحقوق النشر أو العلامة التجارية) لشركة Insure أو الشركات التابعة لها أو الشركاء أو الموردين أو المرخصين للتطبيق. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>سياسة الاسترجاع والاسترداد {"\n"}{"\n"}</Text>
                 

شكرًا على التسوق في Insure. نحن نقدر حقيقة أنك تحب شراء الأشياء التي نبنيها. نريد أيضًا التأكد من حصولك على تجربة مجزية أثناء استكشاف منتجاتنا وتقييمها وشرائها. 

 

كما هو الحال مع أي تجربة تسوق ، هناك شروط وأحكام تنطبق على المعاملات في Insure. سنكون موجزين بقدر ما يسمح محامونا. الشيء الرئيسي الذي يجب تذكره هو أنه من خلال تقديم طلب أو إجراء عملية شراء في Insure ، فإنك توافق على الشروط جنبًا إلى جنب مع سياسة خصوصية Insure. 

 

إذا لم تكن راضيًا تمامًا لأي سبب من الأسباب عن أي سلعة أو خدمة نقدمها ، فلا تتردد في الاتصال بنا وسنناقش أيًا من المشكلات التي تواجهها مع منتجنا. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>أنت من الاقتراحات {"\n"}{"\n"}</Text>


تظل أي تعليقات أو تعليقات أو أفكار أو تحسينات أو اقتراحات (يشار إليها مجتمعة باسم "الاقتراحات") تقدمها إلى Insure فيما يتعلق بالتطبيق ملكية حصرية لشركة Insure. 

 

 

يتمتع Insure بحرية استخدام أو نسخ أو تعديل أو نشر أو إعادة توزيع الاقتراحات لأي غرض وبأي شكل من الأشكال دون أي ائتمان أو أي تعويض لك. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>أنت موافق {"\n"}{"\n"}</Text>


لقد قمنا بتحديث الشروط والأحكام الخاصة بنا لتزويدك بشفافية كاملة فيما يتعلق بما يتم تعيينه عند زيارة موقعنا وكيفية استخدامه. باستخدام تطبيقنا أو تسجيل حساب أو إجراء عملية شراء ، فإنك بذلك توافق على الشروط والأحكام الخاصة بنا. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>أروابط لمواقع أخرى{"\n"}{"\n"}</Text>


تنطبق هذه الشروط والأحكام على الخدمات فقط. قد تحتوي الخدمات على روابط لمواقع أخرى لا تديرها شركة Insure أو تتحكم فيها. نحن لسنا مسؤولين عن المحتوى أو الدقة أو الآراء المعبر عنها في مثل هذه المواقع ، ولا يتم التحقيق في هذه المواقع أو مراقبتها أو التحقق من دقتها أو اكتمالها من قبلنا. يرجى تذكر أنه عند استخدام ارتباط للانتقال من الخدمات إلى موقع ويب آخر ، فإن الشروط والأحكام الخاصة بنا لم تعد سارية. أنت تتصفح وتتفاعل على أي موقع ويب آخر ، بما في ذلك المواقع التي تحتوي على رابط على نظامنا الأساسي ، ويخضع لقواعد وسياسات هذا الموقع. قد تستخدم هذه الأطراف الثالثة ملفات تعريف الارتباط الخاصة بها أو طرق أخرى لجمع معلومات عنك. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>أبسكويت {"\n"}{"\n"}</Text>


تستخدم Insure "ملفات تعريف الارتباط" لتحديد مناطق موقعنا على الويب التي قمت بزيارتها. ملف تعريف الارتباط هو جزء صغير من البيانات المخزنة على جهاز الكمبيوتر أو الجهاز المحمول الخاص بك بواسطة متصفح الويب الخاص بك. نحن نستخدم ملفات تعريف الارتباط لتحسين أداء ووظائف تطبيقنا ولكنها غير ضرورية لاستخدامها. ومع ذلك ، بدون ملفات تعريف الارتباط هذه ، قد تصبح وظائف معينة مثل مقاطع الفيديو غير متاحة أو قد يُطلب منك إدخال تفاصيل تسجيل الدخول الخاصة بك في كل مرة تزور فيها التطبيق حيث لن نتمكن من تذكر أنك قمت بتسجيل الدخول مسبقًا. يمكن ضبط معظم متصفحات الويب لتعطيل استخدام ملفات تعريف الارتباط. ومع ذلك ، إذا قمت بتعطيل ملفات تعريف الارتباط ، فقد لا تتمكن من الوصول إلى الوظائف الموجودة على موقعنا بشكل صحيح أو على الإطلاق. لا نضع أبدًا معلومات تعريف شخصية في ملفات تعريف الارتباط. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>التغييرات على الشروط والأحكام الخاصة بنا {"\n"}{"\n"}</Text> 


أنت تقر وتوافق على أن شركة التأمين ؛ قد تتوقف (بشكل دائم أو مؤقت) عن تقديم الخدمة (أو أي ميزات داخل الخدمة) لك أو للمستخدمين بشكل عام وفقًا لتقدير شركة التأمين وحدها ، دون إشعار مسبق لك. يمكنك التوقف عن استخدام الخدمة في أي وقت. لا تحتاج إلى إبلاغ Insure على وجه التحديد ؛ عندما تتوقف عن استخدام الخدمة. أنت تقر وتوافق على أنه إذا تأمين ؛ تعطيل الوصول إلى حسابك ، فقد يتم منعك من الوصول إلى الخدمة أو تفاصيل حسابك أو أي ملفات أو مواد أخرى موجودة في حسابك.                 

إذا قررنا تغيير الشروط والأحكام الخاصة بنا ، فسنقوم بنشر هذه التغييرات على هذه الصفحة و / أو تحديث تاريخ تعديل الشروط والأحكام أدناه. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>اتعديلات على التطبيق لدينا {"\n"}{"\n"}</Text>                 


تحتفظ Insure بالحق في تعديل التطبيق أو أي خدمة تتصل بها أو تعليقها أو إيقافها ، بشكل مؤقت أو دائم ، بإشعار أو بدون إشعار ودون مسؤولية تجاهك. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>اتحديثات لتطبيقنا {"\n"}{"\n"}</Text>                  
                 

قد تقدم Insure من وقت لآخر تحسينات أو تحسينات على ميزات / وظائف التطبيق ، والتي قد تتضمن تصحيحات وإصلاحات أخطاء وتحديثات وترقيات وتعديلات أخرى ("التحديثات"). 

 

 

قد تقوم التحديثات بتعديل أو حذف بعض الميزات و / أو وظائف التطبيق. أنت توافق على أن Insure ليست ملزمة بـ (1) تقديم أي تحديثات ، أو (2) الاستمرار في توفير أو تمكين أي ميزات و / أو وظائف معينة للتطبيق لك. 

 

أنت توافق أيضًا على أن جميع التحديثات (1) ستُعتبر جزءًا لا يتجزأ من التطبيق ، و (2) تخضع لبنود وشروط هذه الاتفاقية. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>اخدمات الطرف الثالث {"\n"}{"\n"}</Text>   


يجوز لنا عرض محتوى جهة خارجية أو تضمينه أو توفيره (بما في ذلك البيانات والمعلومات والتطبيقات وخدمات المنتجات الأخرى) أو توفير روابط لمواقع أو خدمات الطرف الثالث ("خدمات الطرف الثالث"). 

 

 

أنت تقر وتوافق على أن Insure لن تكون مسؤولة عن أي خدمات لأطراف أخرى ، بما في ذلك دقتها واكتمالها وصلاحيتها وامتثالها لحقوق الطبع والنشر والشرعية واللياقة والجودة أو أي جانب آخر من هذه الخدمات. لا تتحمل Insure ولن تتحمل أي التزام أو مسؤولية تجاهك أو تجاه أي شخص أو كيان آخر عن أي خدمات لأطراف أخرى. 

 

 

 

يتم توفير خدمات الطرف الثالث والروابط الخاصة به فقط من أجل الراحة لك ويمكنك الوصول إليها واستخدامها بالكامل على مسؤوليتك الخاصة وتخضع لشروط وأحكام هذه الأطراف الثالثة. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>االمدة والإنهاء {"\n"}{"\n"}</Text>                  
                تظل هذه الاتفاقية سارية المفعول حتى يتم إنهاؤها بواسطتك أو بواسطة المؤمن. 

 

يجوز لشركة التأمين ، وفقًا لتقديرها الخاص ، في أي وقت ولأي سبب أو بدون سبب ، تعليق أو إنهاء هذه الاتفاقية بإخطار مسبق أو بدونه. 

 

 

ستنتهي هذه الاتفاقية على الفور ، دون إشعار مسبق من شركة التأمين ، في حالة عدم امتثالك لأي حكم من أحكام هذه الاتفاقية. يمكنك أيضًا إنهاء هذه الاتفاقية عن طريق حذف التطبيق وجميع نسخه من جهاز الكمبيوتر الخاص بك. 

 

 

عند إنهاء هذه الاتفاقية ، يجب عليك التوقف عن استخدام التطبيق بالكامل وحذف جميع نسخ التطبيق من جهاز الكمبيوتر الخاص بك. 

 

 

 

لن يحد إنهاء هذه الاتفاقية من أي من حقوق المؤمن له أو تعويضاته بموجب القانون أو في حقوق الملكية في حالة قيامك بخرق أي من التزاماتك بموجب هذه الاتفاقية (خلال مدة هذه الاتفاقية). 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>اإشعار انتهاك حقوق النشر {"\n"}{"\n"}</Text>     
                 

إذا كنت مالكًا لحقوق الطبع والنشر أو وكيلًا للمالك وتعتقد أن أي مادة على تطبيقنا تشكل انتهاكًا لحقوق الطبع والنشر الخاصة بك ، فيرجى الاتصال بنا مع توضيح المعلومات التالية: (أ) توقيعًا ماديًا أو إلكترونيًا لمالك حقوق الطبع والنشر أو شخص مخول بذلك التصرف نيابة عنه ؛ (ب) تحديد المواد التي يُدعى أنها منتهِكة ؛ (ج) معلومات الاتصال الخاصة بك ، بما في ذلك العنوان ورقم الهاتف والبريد الإلكتروني ؛ (د) تصريح من جانبك بأن لديك اعتقاد حسن النية بأن استخدام المواد غير مصرح به من قبل مالكي حقوق النشر ؛ و (هـ) الإفادة بأن المعلومات الواردة في الإشعار دقيقة ، وتحت طائلة عقوبة الحنث باليمين ، يحق لك التصرف نيابة عن المالك. 

 

 

 

 

 

التعويض 

 

أنت توافق على تعويض شركة Insure ووالديها ، والشركات التابعة لها ، والشركات التابعة لها ، والمسؤولين ، والموظفين ، والوكلاء ، والشركاء ، والمرخصين (إن وجد) ، وإبقاء التأمين غير ضار من أي مطالبة أو طلب ، بما في ذلك أتعاب المحاماة المعقولة ، بسبب أو الناشئة عن: (أ) استخدام التطبيق ؛ (ب) انتهاك هذه الاتفاقية أو أي قانون أو لائحة ؛ أو (ج) انتهاك أي حق لطرف ثالث. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>لا توجد ضمانات {"\n"}{"\n"}</Text>      
                 

التطبيق مقدم لكم "كما هو" و "كما هو متوفر" وبكافة العيوب والعيوب بدون ضمان من أي نوع. إلى أقصى حد يسمح به القانون المعمول به ، تتنصل Insure ، بالأصالة عن نفسها وبالنيابة عن الشركات التابعة لها ومرخصيها ومقدمي الخدمات المعنيين ، صراحةً من جميع الضمانات ، سواء كانت صريحة أو ضمنية أو قانونية أو غير ذلك ، فيما يتعلق التطبيق ، بما في ذلك جميع الضمانات الضمنية الخاصة بالتسويق ، والملاءمة لغرض معين ، والملكية وعدم الانتهاك ، والضمانات التي قد تنشأ عن سياق التعامل أو مسار الأداء أو الاستخدام أو الممارسة التجارية. على سبيل المثال لا الحصر ، لا تقدم Insure أي ضمان أو تعهد ولا تقدم أي تمثيل من أي نوع بأن التطبيق سوف يلبي متطلباتك أو يحقق أي نتائج مقصودة أو يكون متوافقًا أو يعمل مع أي برامج أو أنظمة أو خدمات أخرى ، ويعمل دون انقطاع ، تستوفي أي معايير أداء أو موثوقية أو أن تكون خالية من الأخطاء أو أن أي أخطاء أو عيوب يمكن أو سيتم تصحيحها. 

 

 

 

 

 

 

 

بدون تقييد ما سبق ، لا تقدم شركة Insure ولا أي مزود تابع لها أي تمثيل أو ضمان من أي نوع ، صريحًا أو ضمنيًا: (1) فيما يتعلق بتشغيل أو توفر التطبيق ، أو المعلومات ، والمحتوى ، والمواد أو المنتجات المدرجة فيه ؛ (2) أن التطبيق لن ينقطع أو سيكون خاليًا من الأخطاء ؛ (3) فيما يتعلق بدقة أو موثوقية أو حداثة أي معلومات أو محتوى مقدم من خلال التطبيق ؛ أو (4) أن التطبيق أو خوادمه أو المحتوى أو رسائل البريد الإلكتروني المرسلة من Insure أو بالنيابة عنها خالية من الفيروسات أو البرامج النصية أو أحصنة طروادة أو الفيروسات المتنقلة أو البرامج الضارة أو القنابل الزمنية أو المكونات الضارة الأخرى. 

 

 

 

 

لا تسمح بعض الولايات القضائية باستثناء الضمانات الضمنية أو القيود المفروضة عليها أو القيود المفروضة على الحقوق القانونية المعمول بها للمستهلك ، لذلك قد لا تنطبق عليك بعض أو كل الاستثناءات والقيود المذكورة أعلاه. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>تحديد المسؤولية {"\n"}{"\n"}</Text>      


بصرف النظر عن أي أضرار قد تتكبدها ، فإن المسؤولية الكاملة لشركة التأمين وأي من مورديه بموجب أي حكم من أحكام هذه الاتفاقية والتعويض الحصري لكل ما سبق يجب أن يقتصر على المبلغ الذي دفعته بالفعل مقابل التطبيق. 

 

 

إلى أقصى حد يسمح به القانون المعمول به ، لن تتحمل شركة التأمين أو مورديها بأي حال من الأحوال المسؤولية عن أي أضرار خاصة أو عرضية أو غير مباشرة أو تبعية من أي نوع (بما في ذلك ، على سبيل المثال لا الحصر ، الأضرار الناجمة عن خسارة الأرباح أو فقدان البيانات أو معلومات أخرى ، لتوقف العمل ، للإصابة الشخصية ، لفقدان الخصوصية الناشئ عن أو بأي طريقة تتعلق باستخدام أو عدم القدرة على استخدام التطبيق ، و / أو برامج الطرف الثالث و / أو أجهزة الطرف الثالث المستخدمة مع التطبيق ، أو فيما يتعلق بأي حكم من أحكام هذه الاتفاقية) ، حتى لو تم إخطار المؤمن أو أي مورد بإمكانية حدوث مثل هذه الأضرار وحتى إذا فشل العلاج في تحقيق غرضه الأساسي. 

 

 

 

 

 

لا تسمح بعض الولايات / الولايات القضائية باستثناء أو تقييد الأضرار العرضية أو التبعية ، لذلك قد لا ينطبق عليك التقييد أو الاستثناء أعلاه. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>الاستقلالية {"\n"}{"\n"}</Text>     


إذا تم اعتبار أي بند من أحكام هذه الاتفاقية غير قابل للتنفيذ أو غير صالح ، فسيتم تغيير هذا الحكم وتفسيره لتحقيق أهداف هذا الحكم إلى أقصى حد ممكن بموجب القانون المعمول به وستظل الأحكام المتبقية سارية المفعول والتأثير الكامل. 

 

 

 

تشكل هذه الاتفاقية ، جنبًا إلى جنب مع سياسة الخصوصية وأي إشعارات قانونية أخرى تنشرها شركة Insure على الخدمات ، الاتفاقية الكاملة بينك وبين شركة Insure فيما يتعلق بالخدمات. إذا تم اعتبار أي حكم من أحكام هذه الاتفاقية غير صالح من قبل محكمة ذات اختصاص قضائي ، فإن بطلان هذا الحكم لا يؤثر على صحة الأحكام المتبقية من هذه الاتفاقية ، والتي تظل سارية المفعول والتأثير الكامل. لا يُعتبر أي تنازل عن أي بند من بنود هذه الاتفاقية بمثابة تنازل إضافي أو مستمر عن هذا الشرط أو أي شرط آخر ، ولا يشكل فشل شركة التأمين في تأكيد أي حق أو حكم بموجب هذه الاتفاقية تنازلاً عن هذا الحق أو الحكم. توافق أنت و Insure على أن أي سبب من دعاوى الدعوى الناشئة عن الخدمات أو المتعلقة بها يجب أن يبدأ خلال عام واحد (1) بعد قبول سبب الدعوى. من ناحية اخري. تصرف مثل ذلك ممنوع دائما. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>تنازل {"\n"}{"\n"}</Text>  


باستثناء ما هو منصوص عليه في هذه الاتفاقية ، فإن الإخفاق في ممارسة حق أو المطالبة بأداء التزام بموجب هذه الاتفاقية لا يؤثر على قدرة الطرف على ممارسة هذا الحق أو يتطلب مثل هذا الأداء في أي وقت بعد ذلك ولا يشكل التنازل عن خرق تنازلاً عن أي خرق لاحق. 

 

 

 

لا يجوز لأي إخفاق في ممارسة ولا تأخير في ممارسة ، من جانب أي من الطرفين ، أي حق أو أي سلطة بموجب هذه الاتفاقية بمثابة تنازل عن هذا الحق أو السلطة. ولا يجوز أن تمنع أي ممارسة فردية أو جزئية لأي حق أو سلطة بموجب هذه الاتفاقية ممارسة أخرى لذلك أو أي حق آخر ممنوح بموجب هذه الاتفاقية. في حالة وجود تعارض بين هذه الاتفاقية وأي عملية شراء سارية أو شروط أخرى ، تسري شروط هذه الاتفاقية. 
                {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>التعديلات على هذه الاتفاقية {"\n"}{"\n"}</Text>  


تحتفظ Insure بالحق ، وفقًا لتقديرها الخاص ، في تعديل أو استبدال هذه الاتفاقية في أي وقت. إذا كانت المراجعة مادة ، فسنقدم إشعارًا قبل 30 يومًا على الأقل قبل دخول أي شروط جديدة حيز التنفيذ. سيتم تحديد ما يشكل تغييرًا جوهريًا وفقًا لتقديرنا الخاص. 

من خلال الاستمرار في الوصول إلى تطبيقنا أو استخدامه بعد أن تصبح أي مراجعات فعالة ، فإنك توافق على الالتزام بالشروط المعدلة. إذا كنت لا توافق على الشروط الجديدة ، فلم يعد مسموحًا لك باستخدام Insure. 
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>ااتفاق كامل {"\n"}{"\n"}</Text>                      
               

تشكل الاتفاقية الاتفاقية الكاملة بينك وبين Insure فيما يتعلق باستخدامك للتطبيق وتحل محل جميع الاتفاقيات الكتابية أو الشفوية السابقة والمعاصرة بينك وبين Insure. 

 

قد تخضع لبنود وشروط إضافية تسري عند استخدامك أو شرائك لخدمات المؤمن الأخرى ، والتي سيقدمها لك Insure في وقت هذا الاستخدام أو الشراء. 
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>اتحديثات على شروطنا {"\n"}{"\n"}</Text> 
              يجوز لنا تغيير خدمتنا وسياساتنا ، وقد نحتاج إلى إجراء تغييرات على هذه الشروط بحيث تعكس خدماتنا وسياساتنا بدقة. ما لم يقتض القانون خلاف ذلك ، سنخطرك (على سبيل المثال ، من خلال خدمتنا) قبل إجراء تغييرات على هذه الشروط ونمنحك فرصة لمراجعتها قبل أن تدخل حيز التنفيذ. بعد ذلك ، إذا واصلت استخدام الخدمة ، فسوف تلتزم بالشروط المحدثة. إذا كنت لا تريد الموافقة على هذه الشروط أو أي شروط محدثة ، يمكنك حذف حسابك. 
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>االملكية الفكرية {"\n"}{"\n"}</Text>


التطبيق ومحتوياته بالكامل وميزاته ووظائفه (بما في ذلك على سبيل المثال لا الحصر جميع المعلومات والبرامج والنصوص وشاشات العرض والصور والفيديو والصوت والتصميم والاختيار والترتيب) ، مملوكة لشركة Insure ومرخصيها ، أو غيرهم من مقدمي هذه المواد وتحميهم دولة الإمارات العربية المتحدة وقوانين حقوق النشر والعلامات التجارية وبراءات الاختراع والأسرار التجارية وغيرها من قوانين حقوق الملكية الفكرية أو حقوق الملكية الدولية. لا يجوز نسخ المواد أو تعديلها أو إعادة إنتاجها أو تنزيلها أو توزيعها بأي شكل من الأشكال ، كليًا أو جزئيًا ، دون الحصول على إذن كتابي صريح مسبق من Insure ، ما لم يتم النص على ذلك صراحةً في هذه الشروط والأحكام وباستثناء ما هو منصوص عليه صراحةً. يحظر أي استخدام غير مصرح به للمواد. 
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>ااتفاق التحكيم {"\n"}{"\n"}</Text>


ينطبق هذا القسم على أي نزاع باستثناء أنه لا يتضمن نزاعًا يتعلق بالمطالبات بالإعفاء غير القانوني أو المنصف فيما يتعلق بإنفاذ أو صلاحية حقوق الملكية الفكرية الخاصة بك أو شركة التأمين. يُقصد بمصطلح "نزاع" أي نزاع أو إجراء أو خلافات أخرى بينك وبين شركة Insure فيما يتعلق بالخدمات أو هذه الاتفاقية ، سواء في العقد أو الضمان أو الضرر أو التشريع أو اللوائح أو المرسوم أو أي أساس قانوني أو عادل آخر. سيتم إعطاء "النزاع" أوسع معنى ممكن يسمح به القانون. 
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>إشعار النزاع {"\n"}{"\n"}</Text>
               

في حالة حدوث نزاع ، يجب عليك أنت أو المؤمن له تقديم إشعار نزاع للآخر ، وهو بيان مكتوب يوضح الاسم والعنوان ومعلومات الاتصال الخاصة بالطرف الذي يقدمه ، والحقائق التي أدت إلى النزاع ، و طلب الإغاثة. يجب عليك إرسال أي إشعار بالنزاع عبر البريد الإلكتروني إلى: info@gfs.ae. سوف ترسل Insure لك إشعار نزاع بالبريد إلى عنوانك إذا كان لدينا ، أو إلى عنوان بريدك الإلكتروني. ستحاول أنت و Insure حل أي نزاع من خلال التفاوض غير الرسمي في غضون ستين (60) يومًا من تاريخ إرسال إشعار النزاع. بعد ستين (60) يومًا ، يمكنك أنت أو المؤمن له بدء التحكيم. 
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>التحكيم الملزم {"\n"}{"\n"}</Text>


إذا لم تقم أنت و Insure بحل أي نزاع عن طريق التفاوض غير الرسمي ، فسيتم إجراء أي جهد آخر لحل النزاع حصريًا عن طريق التحكيم الملزم كما هو موضح في هذا القسم. أنت تتنازل عن الحق في التقاضي (أو المشاركة كطرف أو عضو في الفصل) في جميع النزاعات في المحكمة أمام قاضٍ أو هيئة محلفين. يتم تسوية النزاع عن طريق التحكيم الملزم وفقًا لقواعد التحكيم التجاري لجمعية التحكيم الأمريكية. يجوز لأي من الطرفين السعي للحصول على أي تعويض قضائي مؤقت أو أولي من أي محكمة ذات اختصاص قضائي ، حسب الضرورة لحماية حقوق الطرف أو ممتلكاته في انتظار الانتهاء من التحكيم. يتحمل الطرف غير الفائز أي وجميع التكاليف القانونية والمحاسبية وغيرها من التكاليف والرسوم والنفقات التي يتكبدها الطرف السائد.
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>اعمليات الإرسال والخصوصية {"\n"}{"\n"}</Text>             


في حالة إرسال أو نشر أي أفكار أو اقتراحات إبداعية أو تصميمات أو صور فوتوغرافية أو معلومات أو إعلانات أو بيانات أو مقترحات ، بما في ذلك أفكار لمنتجات أو خدمات أو ميزات أو تقنيات أو عروض ترويجية جديدة أو محسّنة ، فأنت توافق صراحةً على أن هذه الطلبات سيتم التعامل معها تلقائيًا على أنها غير سرية وغير مملوكة وسيصبح الملكية الوحيدة لشركة Insure دون أي تعويض أو ائتمان لك على الإطلاق. لا تتحمل شركة Insure والشركات التابعة لها أية التزامات فيما يتعلق بهذه الطلبات أو المنشورات وقد تستخدم الأفكار الواردة في مثل هذه المشاركات أو المنشورات لأي أغراض في أي وسيط إلى الأبد ، بما في ذلك ، على سبيل المثال لا الحصر ، تطوير وتصنيع وتسويق المنتجات و الخدمات باستخدام مثل هذه الأفكار. 
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>االترقيات {"\n"}{"\n"}</Text> 


يجوز لشركة التأمين ، من وقت لآخر ، تضمين المسابقات أو العروض الترويجية أو اليانصيب أو الأنشطة الأخرى ("العروض الترويجية") التي تتطلب منك تقديم مواد أو معلومات تتعلق بنفسك. يرجى ملاحظة أن جميع العروض الترويجية قد تكون محكومة بقواعد منفصلة قد تحتوي على متطلبات أهلية معينة ، مثل القيود المفروضة على العمر والموقع الجغرافي. أنت مسؤول عن قراءة جميع قواعد العروض الترويجية لتحديد ما إذا كنت مؤهلاً للمشاركة أم لا. إذا قمت بإدخال أي عرض ترويجي ، فإنك توافق على الالتزام والامتثال لجميع قواعد العروض الترويجية.  

قد يتم تطبيق شروط وأحكام إضافية على مشتريات السلع أو الخدمات على الخدمات أو من خلالها ، والتي تعتبر الشروط والأحكام جزءًا من هذه الاتفاقية بموجب هذا المرجع. 
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>أخطاء مطبعية {"\n"}{"\n"}</Text> 
              ي حالة إدراج منتج و / أو خدمة بسعر غير صحيح أو بمعلومات غير صحيحة بسبب خطأ مطبعي ، يحق لنا رفض أو إلغاء أي طلبات مقدمة للمنتج و / أو الخدمة المدرجة بسعر غير صحيح. يحق لنا رفض أو إلغاء أي طلب من هذا القبيل سواء تم تأكيد الطلب أم لا وشحن بطاقتك الائتمانية. إذا تم بالفعل خصم رسوم الشراء من بطاقتك الائتمانية وتم إلغاء طلبك ، فسنصدر على الفور رصيدًا إلى حساب بطاقتك الائتمانية أو حسابات الدفع الأخرى بمبلغ الرسوم. 
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>أمتفرقات {"\n"}{"\n"}</Text> 


إذا وجدت محكمة مختصة لأي سبب من الأسباب أن أي حكم أو جزء من هذه الشروط والأحكام غير قابل للتنفيذ ، فستظل بقية هذه الشروط والأحكام سارية المفعول والتأثير الكامل. لن يكون أي تنازل عن أي شرط من هذه الشروط والأحكام ساريًا إلا إذا كان مكتوبًا وموقعًا من قبل ممثل مفوض من شركة التأمين. يحق للمؤمن الحصول على أمر زجري أو أي تعويض إنصافي آخر (بدون التزامات بنشر أي تعهد أو ضمان) في حالة حدوث أي خرق أو خرق متوقع من جانبك. تقوم Insure بتشغيل ومراقبة خدمة التأمين من مكاتبها في دولة الإمارات العربية المتحدة. الخدمة غير مخصصة للتوزيع أو الاستخدام من قبل أي شخص أو كيان في أي ولاية قضائية أو بلد حيث يكون هذا التوزيع أو الاستخدام مخالفًا للقانون أو اللوائح. وبناءً على ذلك ، فإن هؤلاء الأشخاص الذين يختارون الوصول إلى خدمة التأمين من مواقع أخرى يفعلون ذلك بمبادرتهم الخاصة وهم وحدهم المسؤولون عن الامتثال للقوانين المحلية ، إذا كانت القوانين المحلية قابلة للتطبيق وإلى الحد الأقصى. تحتوي هذه الشروط والأحكام (التي تتضمن وتتضمن سياسة خصوصية Insure) على الفهم الكامل وتحل محل جميع التفاهمات السابقة بينك وبين Insure فيما يتعلق بموضوعها ، ولا يمكنك تغييرها أو تعديلها. عناوين الأقسام المستخدمة في هذه الاتفاقية هي للتسهيل فقط ولن يتم استيرادها بشكل قانوني. 
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>تنصل {"\n"}{"\n"}</Text>      
              يست مسؤولة عن أي محتوى أو رمز أو أي عدم دقة أخرى. 

 

لا تقدم شركة Insure أي ضمانات أو ضمانات. 

 

لن تكون شركة التأمين مسؤولة بأي حال من الأحوال عن أي أضرار خاصة أو مباشرة أو غير مباشرة أو تبعية أو عرضية أو أي أضرار من أي نوع ، سواء في عقد أو إهمال أو أضرار أخرى ، تنشأ عن أو فيما يتعلق باستخدام الخدمة أو محتويات الخدمة. تحتفظ Insure بالحق في إجراء إضافات أو حذف أو تعديلات على محتويات الخدمة في أي وقت دون إشعار مسبق. 

 

 

 

 

يتم توفير خدمة التأمين ومحتوياتها "كما هي" و "كما هي متوفرة" دون أي ضمان أو إقرارات من أي نوع ، سواء كانت صريحة أو ضمنية. Insure هو موزع وليس ناشر للمحتوى المقدم من أطراف ثالثة ؛ على هذا النحو ، لا تمارس Insure أي سيطرة تحريرية على هذا المحتوى ولا تقدم أي ضمان أو تمثيل فيما يتعلق بدقة أو موثوقية أو عملة أي معلومات أو محتوى أو خدمة أو بضائع مقدمة من خلال خدمة التأمين أو يمكن الوصول إليها عبرها. بدون تقييد ما سبق ، تخلي Insure مسؤوليتها تحديدًا عن جميع الضمانات والإقرارات في أي محتوى يتم نقله على خدمة التأمين أو فيما يتعلق بها أو على المواقع التي قد تظهر كروابط على خدمة التأمين ، أو في المنتجات المقدمة كجزء من ، أو في الاتصال بخدمة التأمين ، بما في ذلك على سبيل المثال لا الحصر أي ضمانات خاصة بالتسويق أو الملاءمة لغرض معين أو عدم التعدي على حقوق الطرف الثالث. لن تُنشئ أية مشورة شفهية أو معلومات مكتوبة مقدمة من شركة التأمين أو أي من الشركات التابعة لها أو موظفيها أو مسؤوليها أو مديريها أو وكلائها أو ما شابه ذلك ضمانًا. معلومات السعر والتوافر عرضة للتغيير دون إشعار. بدون تقييد ما سبق ، لا تضمن Insure أن خدمة التأمين ستكون غير منقطعة أو غير معطوبة أو في الوقت المناسب أو خالية من الأخطاء. 
              {"\n"}{"\n"}<Text style={{ color: '#3C2949', fontWeight: 'bold', fontSize: 14 }}>اتصل بنا {"\n"}{"\n"}</Text>


لا تتردد في الاتصال بنا إذا كان لديك أي أسئلة. 

- عبر البريد الإلكتروني: info@gfs.ae 
            </Text>
             {/*</CardItem>*/}
          </Card>
          </View>
        </Content>

        <TouchableOpacity onPress={() => { this.props.navigation.navigate('Register', { test: 'Test' }) }} style={styles.fab}>
                  <Text style={styles.fabIcon}><Icon size={ 18 } name='sign-in'/> ACCEPT AND REGISTER</Text>
                </TouchableOpacity>
        {/*<Footer>
          <FooterTab style={{ backgroundColor: '#E86143' }}>
            <Button vertical onPress={()=> { this.props.navigation.navigate('Services', { test: 'Test' }) }}>
              <Icon style={{ color: '#3C2949', fontSize: 25 }} name="home" />
              <Text style={{ color: '#3C2949' }}>{ I18n.t('HOME') }</Text>
            </Button>
            <Button vertical onPress={()=> { this.props.navigation.navigate('Languages', { test: 'Test' }) }}>
              <Icon style={{ color: '#3C2949', fontSize: 25 }} name="globe" />
              <Text style={{ color: '#3C2949' }}>{ I18n.t('LANGUAGES') }</Text>
            </Button>
            <Button vertical onPress={()=> { this.props.navigation.navigate('Account', { test: 'Test' }) }}>
              <Icon style={{ color: '#fff', fontSize: 25 }} name="user" />
              <Text style={{ color: '#fff' }}>{ I18n.t('SETTINGS') }</Text>
            </Button>
          </FooterTab>
        </Footer>*/}
      </Container>
    );
  }
}

const styles = StyleSheet.create({
  fab: {
    position: 'absolute',
    width: 220,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    right: 20,
    bottom: 80,
    backgroundColor: '#3C2949',
    borderRadius: 30,
  },
  fabIcon: {
    fontSize: 16,
    color: 'white'
  }
});